export const LocalStorageTwitchToken = 'a'
export const LocalStorageDiscordToken = 'b'
export const LocalStorageGoogleToken = 'c'
export const LocalStorageStateOnceToken = 'd'
export const LocalStorageStayConnected = 'e'
export const LocalStorageGuestToken = 'f'
export const LocalStorageChatHistory = 'g'